[package]
name = "trackthor"
version = "0.1.0"
authors = ["Alessio Sanfratello <sanfra90@gmail.com>"]
edition = "2018"

[lib]
name = "trackthor"
crate-type = ["cdylib"]

[dependencies.pyo3]
version = "0.13.0"
features = ["extension-module"]